---
apiVersion: v1 
kind: Service 
metadata: 
  name: monte-carlo-pi-service3 
spec: 
  type: LoadBalancer 
  ports: 
    - port: 80 
      targetPort: 8080 
  selector: 
    app: monte-carlo-pi-service3 
--- 
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: monte-carlo-pi-service3 
  labels: 
    app: monte-carlo-pi-service3 
spec: 
  replicas: 8
  selector: 
    matchLabels: 
      app: monte-carlo-pi-service3 
  template: 
    metadata: 
      labels: 
        app: monte-carlo-pi-service3 
    spec:
      nodeSelector:
        spotsa3: jp3
      containers: 
        - name: monte-carlo-pi-service3 
          image: ruecarlo/monte-carlo-pi-service
          resources: 
            requests: 
              memory: "512Mi" 
              cpu: "1024m" 
            limits: 
              memory: "512Mi" 
              cpu: "1024m" 
          securityContext: 
            privileged: false 
            readOnlyRootFilesystem: true 
            allowPrivilegeEscalation: false 
          ports: 
            - containerPort: 8080 

